### PR TITLE
Use Linux line ending under windows

### PR DESCRIPTION
**Pull request by jpegger**
When generating script files force linux ending style

### CODE REVIEW

**Comment by maoueh** [comment]
@jpegger Thank you! Would you mind adding an entry to the changelog when you find the time? When doing so, can you describe the actual rational being your changes?

I can do it if you prefer, simply explain the rational here and I will update the changelog after the merge.

**Comment by jpegger** [comment]
@maoueh I use Vagrant on a windows machine. When generating the nugrant2env.sh script  with the following command "vagrant user env --format script" the generated file has windows line ending. I use this file while provisiong my vagrant linux virtual machine but because of the windows line ending the script file doesn't work under linux. Changing the 2 lines in the commit forces binary mode which will keep linux file endings.

**Comment by maoueh** [comment]
Thank you!

**Comment by maoueh** [comment]
Just released `nugrant` `2.1.3` with your fix included.

**Pull request merged**
