### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nvtkaszpir**
Minor fix in formatting.

### CODE REVIEW

**Comment by colbywhite** [comment]
FYI, I think the convention is `Vagrantfile`s

**Comment by nvtkaszpir** [comment]
I was thinking about the same, but I've decided the 's' would stand out and it would look weird.

**Comment by maoueh** [comment]
Or `... to all your 'Vagrantfile' files.`? (Obviously, with the right formatting this time so single quotes into backticks :D).

But I'm not a native English speaker so I'm not sure which option is the more kosher one. I don't have strong feeling about any version.

**Comment by nvtkaszpir** [comment]
Aren't we wasting more time on this than we're supposed to? :D

**Comment by colbywhite** [comment]
> Aren't we wasting more time on this than we're supposed to? :D

Yes. Yes we are. I regret bringing it up.

:shipit: 

(But for the record, I like @maoueh's convention. :smiling_imp:)

**Pull request merged**
